class PlayerSerializer < ActiveModel::Serializer
  attributes :id,
             :full_name,
             :team,
             :pos,
             :age,
             :games,
             :games_started,
             :mpg,
             :fga,
             :fgp,
             :threeP,
             :threePA,
             :threePP,
             :ppg,
             :rpg,
             :apg,
             :spg,
             :bpg,
             :tpg,
             :twoP,
             :twoPA,
             :twoPP,
             :efg,
             :ft,
             :fta,
             :ftp,
             :orb,
             :drb,
             :likeCount
  has_many :comments
end
